### ISSUE TITLE
Criar destaques para o portal Regional BIGG-REC e COVID Therapy

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/artes-graficas#113]
Mensagem Veronica: 

Márcio, bom dia, 
por favor fazer a arte para 2 destaques que devem entrar no Portal Regional da BVS, no dia 24 de agosto. Segue a informação nos 3 idiomas, no arquivo em anexo.
@Pinto, Rosemeire (BIR) por favor incluir na planilha e acompanhar. 
Obrigada,

[destaque BIGG REC e COVID Therapy.docx](https://github.com/bireme/artes-graficas/files/9373835/destaque.BIGG.REC.e.COVID.Therapy.docx)

**Comment by marcioalvessilva** [comment]
Boa tarde @pintoros 

BIGG-REC
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/bigg-rec/JPG
**PT**
![image](https://user-images.githubusercontent.com/48724136/185981193-c334ce84-2e27-4697-a247-e082e47d043a.png)
**ES**
![image](https://user-images.githubusercontent.com/48724136/185981222-410b056d-34c1-42f4-b22a-8c1d3f740c17.png)
**EN**
![image](https://user-images.githubusercontent.com/48724136/185981247-e6d45b65-5eaa-4abc-9620-14842d0f32db.png)


COVID Therapy
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/covid-therapy/JPG
**PT**
![image](https://user-images.githubusercontent.com/48724136/185981346-114364a7-674b-4a55-85b5-214d30aa2e3f.png)
**ES**
![image](https://user-images.githubusercontent.com/48724136/185981370-54e3822a-cadb-432f-a3c6-d7928f3d034d.png)
**EN**
![image](https://user-images.githubusercontent.com/48724136/185981399-9b3c2eea-2d33-4d9a-a0f8-96197ba9fccc.png)

Por favor validar

**Comment by pintoros** [comment]
Márcio, favor corrigir na arte referente a COVID Therapy

Recurso que apresenta o resumo das evidências sobre opções terapêuticas....

Recurso que presenta el resumen de evidencia de las opciones terapéuticas...

Resource that presents therapeutics options summary of evidence...



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:e54f7f9e-4afc-4652-90c7-53b111940760]

________________________________
De: Márcio Alves ***@***.***>
Enviado: segunda-feira, 22 de agosto de 2022 14:23
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/artes-graficas] Criar destaques para o portal Regional BIGG-REC e COVID Therapy (Issue #113)


Boa tarde @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864378856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G%2FrJWDg2H6KTXPQBYH9Zm4%2Bpy8b1WTlJzq3hPF7zJmg%3D&reserved=0>

BIGG-REC
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/bigg-rec/JPG<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Ftree%2Fmain%2Fbanners-sites%2Fregional%2Fbigg-rec%2FJPG&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f9Y48MYsP60bCJXda6LnxM1lLwzES6lpoadK4%2BxELKM%3D&reserved=0>
PT
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981193-c334ce84-2e27-4697-a247-e082e47d043a.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DB98gVtUoEx6A0lJiaPwr%2BnlH9b8e6QzjK4WAlQUY3I%3D&reserved=0>
ES
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981222-410b056d-34c1-42f4-b22a-8c1d3f740c17.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MLoFxzbMfNCF8NmW3Wy1jVqtQAtmcRKlNPqpdppH3no%3D&reserved=0>
EN
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981247-e6d45b65-5eaa-4abc-9620-14842d0f32db.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7%2Bdil48JeZa9z0oxxAt1fV%2BYQiNBbznSD0Pnb4UuiVQ%3D&reserved=0>

COVID Therapy
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/covid-therapy/JPG<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Ftree%2Fmain%2Fbanners-sites%2Fregional%2Fcovid-therapy%2FJPG&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mpgOSP9BpsOIvoRY3B8F43WMDCkTIJsbANOslDW7qzA%3D&reserved=0>
PT
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981346-114364a7-674b-4a55-85b5-214d30aa2e3f.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LhfqmaGyTfp7FnaLTeItUsY5W3so7ES0aNdKBm5wkhI%3D&reserved=0>
ES
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981370-54e3822a-cadb-432f-a3c6-d7928f3d034d.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TrgYkdTYmRGxUR5VXhSIzeJZONJ9sQAGJKv%2BUEU5bQc%3D&reserved=0>
EN
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981399-9b3c2eea-2d33-4d9a-a0f8-96197ba9fccc.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BX97VwG%2B%2FfeNMHuvouTQ%2Fa71kQuzYfLme%2B8izsu3Iks%3D&reserved=0>

Por favor validar

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F113%23issuecomment-1222667116&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864693068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oZxprzzCmENYFsVzOdUiHm87dFKVTg37cr891J0D76Q%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4GGUGOD4V64ELGUPPLV2OZPPANCNFSM565BOQOQ&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864703015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WbQ%2BJLEwv%2Fv4XrkLHlfo7NdnJr6HdrJJ45FVjlf9L4s%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Novo recurso apresenta o resumo de evidências de opções terapêuticas para o manejo da COVID-19

Nuevo recurso presenta el resumen de evidencia de las opciones terapéuticas para el manejo de la COVID-19

New resource presents therapeutics options summary of evidence for the management of COVID-19

Mudei mais um pouquinho kkkkk



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:eb8d412a-91e1-4870-9ed4-b52305d34469]

________________________________
De: Pinto, Rosemeire (BIR) ***@***.***>
Enviado: terça-feira, 23 de agosto de 2022 13:24
Para: bireme/artes-graficas ***@***.***>; bireme/artes-graficas ***@***.***>
Cc: Mention ***@***.***>
Assunto: RE: [bireme/artes-graficas] Criar destaques para o portal Regional BIGG-REC e COVID Therapy (Issue #113)

Márcio, favor corrigir na arte referente a COVID Therapy

Recurso que apresenta o resumo das evidências sobre opções terapêuticas....

Recurso que presenta el resumen de evidencia de las opciones terapéuticas...

Resource that presents therapeutics options summary of evidence...



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:e54f7f9e-4afc-4652-90c7-53b111940760]

________________________________
De: Márcio Alves ***@***.***>
Enviado: segunda-feira, 22 de agosto de 2022 14:23
Para: bireme/artes-graficas ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/artes-graficas] Criar destaques para o portal Regional BIGG-REC e COVID Therapy (Issue #113)


Boa tarde @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864378856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G%2FrJWDg2H6KTXPQBYH9Zm4%2Bpy8b1WTlJzq3hPF7zJmg%3D&reserved=0>

BIGG-REC
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/bigg-rec/JPG<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Ftree%2Fmain%2Fbanners-sites%2Fregional%2Fbigg-rec%2FJPG&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f9Y48MYsP60bCJXda6LnxM1lLwzES6lpoadK4%2BxELKM%3D&reserved=0>
PT
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981193-c334ce84-2e27-4697-a247-e082e47d043a.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DB98gVtUoEx6A0lJiaPwr%2BnlH9b8e6QzjK4WAlQUY3I%3D&reserved=0>
ES
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981222-410b056d-34c1-42f4-b22a-8c1d3f740c17.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MLoFxzbMfNCF8NmW3Wy1jVqtQAtmcRKlNPqpdppH3no%3D&reserved=0>
EN
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981247-e6d45b65-5eaa-4abc-9620-14842d0f32db.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7%2Bdil48JeZa9z0oxxAt1fV%2BYQiNBbznSD0Pnb4UuiVQ%3D&reserved=0>

COVID Therapy
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/covid-therapy/JPG<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Ftree%2Fmain%2Fbanners-sites%2Fregional%2Fcovid-therapy%2FJPG&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mpgOSP9BpsOIvoRY3B8F43WMDCkTIJsbANOslDW7qzA%3D&reserved=0>
PT
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981346-114364a7-674b-4a55-85b5-214d30aa2e3f.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LhfqmaGyTfp7FnaLTeItUsY5W3so7ES0aNdKBm5wkhI%3D&reserved=0>
ES
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981370-54e3822a-cadb-432f-a3c6-d7928f3d034d.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TrgYkdTYmRGxUR5VXhSIzeJZONJ9sQAGJKv%2BUEU5bQc%3D&reserved=0>
EN
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F185981399-9b3c2eea-2d33-4d9a-a0f8-96197ba9fccc.png&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864535095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BX97VwG%2B%2FfeNMHuvouTQ%2Fa71kQuzYfLme%2B8izsu3Iks%3D&reserved=0>

Por favor validar

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F113%23issuecomment-1222667116&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864693068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oZxprzzCmENYFsVzOdUiHm87dFKVTg37cr891J0D76Q%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4GGUGOD4V64ELGUPPLV2OZPPANCNFSM565BOQOQ&data=05%7C01%7Cpintoros%40paho.org%7Cff14c70bc0934bfb220b08da8462f903%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637967857864703015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WbQ%2BJLEwv%2Fv4XrkLHlfo7NdnJr6HdrJJ45FVjlf9L4s%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Atualizações realizada

**Arquivos no GitHub**
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/covid-therapy/JPG


**PT**
![image](https://user-images.githubusercontent.com/48724136/186235364-539ba4d5-954a-475d-bfd2-8f2c8d3aa0b5.png)

**ES**
![image](https://user-images.githubusercontent.com/48724136/186235441-7fcf342e-992d-4f20-a859-a42a14bca34b.png)

**EN**
![image](https://user-images.githubusercontent.com/48724136/186235547-5cf85b6b-2cc2-4bbb-a6b8-2d5ceb53140a.png)

**Comment by marcioalvessilva** [comment]
Finalizado!
