### ISSUE TITLE
Banner - Facebook BVS

### ISSUE THREAD

**Issue by pierrima** [bireme/artes-graficas#27]
Criação de um banner para o perfil BVS no facebook @veronicaabdala

**Comment by pierrima** [comment]
Olá Veronica,

Segue a proposta para o banner do facebook. @veronicaabdala 
![banner](https://user-images.githubusercontent.com/13052947/132923261-b37649b3-5c62-4bf9-a1ac-67ff35d7aaa2.jpg)

**Comment by veronicaabdala** [comment]
Agrega BVS, e outros idiomas?  Pode ter no mesmo banner? Information, Evidence, Network, Cooperacion, Información, Conocimiento, Knowledge, Red, Salud, Health?

**Comment by pierrima** [comment]
Olá Veronica, boa tarde
Segue a proposta com as edições solicitadas. Abraços
![banner2](https://user-images.githubusercontent.com/13052947/133135136-24404c80-8164-4708-9aa9-56275caab3be.jpg)

**Comment by suelisuga** [comment]
@Pierri, Marina de Sene ***@***.***>e @Abdala, Carmen Veronica Mendes ***@***.***>,

Desculpem eu me intrometer, mas não deveríamos incluir LILACS e DeCS na nuvem de palavras visto que não temos facebook específicos para esses produtos?

Obrigada!

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:85bd226d-5d60-47d9-81f5-7da6c25b9a0e]
LILACS 35 años
https://lilacs.bvsalud.org/35anos/es/
[cid:e0dd9bd7-1990-4666-ac8f-46a417c6689b]
________________________________
De: Marina Pierri ***@***.***>
Enviado: lunes, 13 de septiembre de 2021 15:12
Para: bireme/artes-graficas ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [bireme/artes-graficas] Banner - Facebook BVS (#27)


Olá Veronica, boa tarde
Segue a proposta com as edições solicitadas. Abraços
[banner2]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13052947%2F133135136-24404c80-8164-4708-9aa9-56275caab3be.jpg&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660310736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VLDIaFuEP%2Bl%2BKd2k3d%2FyNizmV6dq4m3PmFQyzUERIVc%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F27%23issuecomment-918450130&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660310736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D67v2LuweDy60erfkN%2BK5qIkGdhv2SqL7JADn706pk4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UE5MAR3IBSM3BUVOJ4LUBY5JXANCNFSM5DJSHY2Q&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660320691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8OtI6M658my4MFWsOIk5y%2BcMSxPU1nL7JrrY6DGRKXM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660320691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JHdv0ShvaByIrHtLD3RJaoYYbIcS4N%2FQ9U06%2BRoAmTA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660330647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9ggQp%2F16SkU%2FUr2laEX8jVu%2BZKpVQHAIbjHbP4InsAY%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by suelisuga** [comment]
@Pierri, Marina de Sene ***@***.***>,

Em tempo, achei muito linda a sua arte! ❤️😍

Bjks

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:eb78cfd5-c58c-480d-a5b1-d98441e097fa]
LILACS 35 años
https://lilacs.bvsalud.org/35anos/es/
[cid:8434d06e-f97c-4704-b530-2c405d6f90ce]
________________________________
De: Suga, Sueli Mitiko Yano (BIR) ***@***.***>
Enviado: lunes, 13 de septiembre de 2021 16:22
Para: bireme/artes-graficas ***@***.***>; bireme/artes-graficas ***@***.***>; Pierri, Marina de Sene (BIR) ***@***.***>; Abdala, Carmen Veronica Mendes (BIR) ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: RE: [bireme/artes-graficas] Banner - Facebook BVS (#27)

@Pierri, Marina de Sene ***@***.***>e @Abdala, Carmen Veronica Mendes ***@***.***>,

Desculpem eu me intrometer, mas não deveríamos incluir LILACS e DeCS na nuvem de palavras visto que não temos facebook específicos para esses produtos?

Obrigada!

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:85bd226d-5d60-47d9-81f5-7da6c25b9a0e]
LILACS 35 años
https://lilacs.bvsalud.org/35anos/es/
[cid:e0dd9bd7-1990-4666-ac8f-46a417c6689b]
________________________________
De: Marina Pierri ***@***.***>
Enviado: lunes, 13 de septiembre de 2021 15:12
Para: bireme/artes-graficas ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [bireme/artes-graficas] Banner - Facebook BVS (#27)


Olá Veronica, boa tarde
Segue a proposta com as edições solicitadas. Abraços
[banner2]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13052947%2F133135136-24404c80-8164-4708-9aa9-56275caab3be.jpg&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660310736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VLDIaFuEP%2Bl%2BKd2k3d%2FyNizmV6dq4m3PmFQyzUERIVc%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fartes-graficas%2Fissues%2F27%23issuecomment-918450130&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660310736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D67v2LuweDy60erfkN%2BK5qIkGdhv2SqL7JADn706pk4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UE5MAR3IBSM3BUVOJ4LUBY5JXANCNFSM5DJSHY2Q&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660320691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8OtI6M658my4MFWsOIk5y%2BcMSxPU1nL7JrrY6DGRKXM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660320691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JHdv0ShvaByIrHtLD3RJaoYYbIcS4N%2FQ9U06%2BRoAmTA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csugasuel%40paho.org%7C1231fc8e058b465bec4008d976e215cd%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637671535660330647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9ggQp%2F16SkU%2FUr2laEX8jVu%2BZKpVQHAIbjHbP4InsAY%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pierrima** [comment]
Obrigada @suelisuga ❤️😍
Segue novamente a proposta com as modificações solicitadas.
Abraços
![banner2](https://user-images.githubusercontent.com/13052947/133153857-68bc4d15-1783-4301-8325-75013a532cd8.jpg)

**Comment by veronicaabdala** [comment]
@pierrima gostei, por mim aprovado

**Comment by pierrima** [comment]
Banner publicado no facebook
